version: "3"

services:

  database:
    image: postgres:15.3
    deploy:
      placement:
        constraints: [node.hostname == ${ZYGOTE_HOST}]
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    container_name: ${SYMPORTAL_DATABASE_CONTAINER}

  flask-app:
    build:
      context: ./flask_app
    deploy:
      placement:
        constraints: [node.hostname == ${LINODE_HOST}]
    ports:
      - "5000:5000"
    environment:
      - CONTACT_EMAIL_ADDRESS=${CONTACT_EMAIL_ADDRESS}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SFTP_USERNAME=${SFTP_USERNAME}
      - SFTP_PASSWORD=${SFTP_USERNAME}
      - SFTP_HOME=${SFTP_HOME}
      - SYMPORTAL_DATABASE_CONTAINER=${SYMPORTAL_DATABASE_CONTAINER}
      - SYMPORTAL_SFTP_SERVER_CONTAINER=${SYMPORTAL_SFTP_SERVER_CONTAINER}
    depends_on:
      - database
    container_name: ${SYMPORTAL_FLASK_CONTAINER}

  nginx:
    build:
      context: ./nginx
    deploy:
      placement:
        constraints: [node.hostname == ${LINODE_HOST}]
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SYMPORTAL_FLASK_CONTAINER=${SYMPORTAL_FLASK_CONTAINER}
    volumes:
      - /etc/ssl/symportal:/etc/nginx/certs:ro
    depends_on:
      - flask-app
    container_name: ${SYMPORTAL_NGINX_CONTAINER}

  symportal-framework:
    build:
      context: ./symportal_framework
    deploy:
      placement:
        constraints: [node.hostname == ${ZYGOTE_HOST}]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SFTP_USERNAME=${SFTP_USERNAME}
      - SFTP_PASSWORD=${SFTP_USERNAME}
      - SFTP_HOME=${SFTP_HOME}
      - SYMPORTAL_DATABASE_CONTAINER=${SYMPORTAL_DATABASE_CONTAINER}
      - SYMPORTAL_SFTP_SERVER_CONTAINER=${SYMPORTAL_SFTP_SERVER_CONTAINER}
    command: >
      bash -c "./wait-for-db.sh && tail -f /dev/null"
    depends_on:
      - database
    volumes:
      - /mnt:/mnt
    container_name: ${SYMPORTAL_FRAMEWORK_CONTAINER}

  sftp-server:
    image: atmoz/sftp
    deploy:
      placement:
        constraints: [node.hostname == ${ZYGOTE_HOST}]
    ports:
      - "2222:22"
    environment:
      - SFTP_USERS=${SFTP_USERNAME}:${SFTP_PASSWORD}:${SFTP_UID}:${SFTP_GID}:${SFTP_HOME}
    container_name: ${SYMPORTAL_SFTP_SERVER_CONTAINER}
